### ISSUE TITLE
Trouble with newline

### ISSUE THREAD

**Issue by MrMMorris** [balanced-ops/citadel-ansible#4]
I'm hoping you guys are still maintaining this after the shutdown. This is such a useful plugin.

The problem I am experiencing is I am trying to set a variable using citadel. Here is default/main.yml:

```yaml
hipchat_token: "{{ lookup('citadel', '/sensitive/hipchat_token').strip() }}"
```

What I'm running into, is the citadel plugin is adding a escaped newline because of this:

https://github.com/balanced-ops/citadel-ansible/blob/master/s3lookup.py#L131

The hipchat_token file in the bucket doesn't even have a newline, and yet it is being escaped...

I tried adding .strip('\\\n'), but for some INCREDIBLY frustrating reason, it doesn't do anything:

```yaml
hipchat_token: "{{ lookup('citadel', '/sensitive/hipchat_token').strip('\\n') }}"
```
```yaml
TASK: [tv | debug var=hipchat_token] **************************************
ok: [52.4.115.45] => {
    "var": {
        "hipchat_token": "a1d469abda88fc831205c5e1cea71e\\n"
    }
}
```

and because of the newline characters, hipchat fails with invalid token.

This is a problem for every variable that is a single line.

Any ideas on why strip doesn't work? is there a way around this? Do you even need to use `.encode(unicode-escape)`?
